version: "2"
services:
  web:
    image: meanbee/magento:5.6-apache
    restart: 'always'    
    hostname: magento.docker
    ports:
      - 80:80
    volumes_from:
      - appdata
    environment:
      - VIRTUAL_HOST=magento.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      - ENABLE_SENDMAIL=false
    links:
      - db

  cron:
    image: meanbee/magento:5.6-cli
    restart: 'always'    
    hostname: cron.magento.docker
    working_dir: /var/www/html
    command: /run-cron.sh
    volumes_from:
      - appdata
    environment:
      - ENABLE_SENDMAIL=false
    links:
      - db

  # cli:
  #   image: meanbee/magento:5.6-cli
  #   restart: 'always'
  #   hostname: cli.magento.docker
  #   working_dir: /var/www/html
  #   command: /bin/true
  #   volumes_from:
  #     - appdata
  #   environment:
  #     - AWS_ACCESS_KEY_ID=00000000000000000000
  #     - AWS_SECRET_ACCESS_KEY=0000000000000000000000000000000000000000
  #     - AWS_REGION=eu-west-1
  #     - AWS_BUCKET=magedbm
  #     - AWS_MEDIA_BUCKET=magemm
  #   links:
  #     - db

  db:
    image: meanbee/magento-mysql
    restart: 'always'
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=magento
    volumes:
      - ./mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: 'always'
    links: 
      - db:db
    ports:
      - 8000:80
    environment:
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_ROOT_PASSWORD=magento 

  mail:
    image: mailhog/mailhog
    restart: 'always'
    ports:
      - 1025:1025
      - 8025:8025
    links:
      - web
      - db   

  appdata:
    image: tianon/true
    volumes:
      - ./magento:/var/www/html
